#!/bin/bash 
#查看远程是否挂载了
ret=`findmnt |grep "share_doc" `
if [ ! -z "$ret" ];then
	result="远程已经挂载"
else
	result="远程没有挂载"
fi
#用户选择是否挂载或卸载
dialog --title "挂载或卸载远程机器的硬盘?"	\
		--menu "$result" 20 50 7 \
			"mount" "mount dell machine hard disk" \
			"umount" "umount dell machine hard disk" \
			"remount" "remount dell machine hard disk" \
2>/tmp/tmp.$$
ret=`cat /tmp/tmp.$$`
rm -f /tmp/tmp.$$

clear
src_ip=192.168.15.62
src_dir[1]="share_doc"
dst_dir[1]="/home/hanhj/share_doc"
src_dir[2]="document"
dst_dir[2]="/home/hanhj/document"
n=2
user=hanhj
passwd=hhj123456
#执行挂载或卸载
if [ "$ret" = 'mount' ] ;then
	for i in `seq $n`;do 
		sudo mount -t cifs //${src_ip}/${src_dir[$i]} ${dst_dir[$i]} -o user=${user},pass=${passwd},uid=1000,gid=1000,noserverino,vers=1.0
	done
elif [ "$ret" == 'umount' ];then
	for i in `seq $n`;do 
		sudo umount ${dst_dir[$i]}
	done
elif [ "$ret" == 'remount' ];then
	for i in `seq $n`;do 
		sudo umount ${dst_dir[$i]}
		sudo mount -t cifs //${src_ip}/${src_dir[$i]} ${dst_dir[$i]} -o user=${user},pass=${passwd},uid=1000,gid=1000,noserverino,vers=1.0
	done
fi

ret=`findmnt |grep "share_doc" `
if [ ! -z "$ret" ];then
	result="远程已挂载"
else
	result="远程已卸载"
fi
echo "$result"
